services:
  db:
    image: postgres:17
    container_name: postgres-docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-docker
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker      
    volumes:
      - app_data:/app
      - ./logs:/app/logs
      - ./static:/app/static
      - ./dicom_folders/folder_unprocessed_dicom:/app/folder_unprocessed_dicom
      - ./dicom_folders/folder_for_deidentification:/app/folder_for_deidentification
      - ./dicom_folders/folder_dicom_processing:/app/folder_dicom_processing
      - ./dicom_folders/folder_for_dicom_upload:/app/folder_for_dicom_upload
      - ./dicom_folders/folder_for_dicom_import:/app/folder_for_dicom_import
      - ./dicom_folders/folder_deidentified_rtstruct:/app/folder_deidentified_rtstruct
      - ./dicom_folders/folder_identified_rtstruct:/app/folder_identified_rtstruct
      - ./dicom_folders/folder_post_deidentification:/app/folder_post_deidentification
      - ./dicom_folders/folder_unprocessed_dicom:/app/folder_unprocessed_dicom
      - ./dicom_folders/folder_temp:/app/folder_temp
      - ./dicom_folders/folder_archive:/app/folder_archive
      - /mnt/share/dicom_processing_test/datastore:/app/datastore # Modify this line to match the path of the datastore for the machine. Keep the /app/datastore path as it is as it will map to a specific directory inside the container.
    command: ["./entrypoint.docker.sh"]

  celery:
    build: .
    container_name: celery-docker
    command: ["./entrypoint.docker.sh", "celery"]
    volumes:
      - app_data:/app
      - ./static:/app/static
      - ./logs:/app/logs
      - ./dicom_folders/folder_unprocessed_dicom:/app/folder_unprocessed_dicom
      - ./dicom_folders/folder_for_deidentification:/app/folder_for_deidentification
      - ./dicom_folders/folder_dicom_processing:/app/folder_dicom_processing
      - ./dicom_folders/folder_for_dicom_upload:/app/folder_for_dicom_upload
      - ./dicom_folders/folder_for_dicom_import:/app/folder_for_dicom_import
      - ./dicom_folders/folder_deidentified_rtstruct:/app/folder_deidentified_rtstruct
      - /mnt/share/dicom_processing_test/datastore:/app/datastore # Modify this line to match the path of the datastore for the machine. Keep the /app/datastore path as it is as it will map to a specific directory inside the container.
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      django-web:
        condition: service_started
      rabbitmq:
        condition: service_started

  celery-beat:
    build: .
    container_name: celery-beat-docker
    command: ["./entrypoint.docker.sh", "celery-beat"]
    volumes:
      - app_data:/app
      - ./static:/app/static
      - ./logs:/app/logs
      - ./dicom_folders/folder_unprocessed_dicom:/app/folder_unprocessed_dicom
      - ./dicom_folders/folder_for_deidentification:/app/folder_for_deidentification
      - ./dicom_folders/folder_dicom_processing:/app/folder_dicom_processing
      - ./dicom_folders/folder_for_dicom_upload:/app/folder_for_dicom_upload
      - ./dicom_folders/folder_for_dicom_import:/app/folder_for_dicom_import
      - ./dicom_folders/folder_deidentified_rtstruct:/app/folder_deidentified_rtstruct
      - ./dicom_folders/folder_identified_rtstruct:/app/folder_identified_rtstruct
      - ./dicom_folders/folder_post_deidentification:/app/folder_post_deidentification
      - ./dicom_folders/folder_unprocessed_dicom:/app/folder_unprocessed_dicom
      - ./dicom_folders/folder_temp:/app/folder_temp
      - ./dicom_folders/folder_archive:/app/folder_archive      
      - /mnt/share/dicom_processing_test/datastore:/app/datastore # Modify this line to match the path of the datastore for the machine. Keep the /app/datastore path as it is as it will map to a specific directory inside the container.
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      django-web:
        condition: service_started
      rabbitmq:
        condition: service_started

  frontend-proxy:
    image: nginx:latest
    container_name: nginx-docker
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web
volumes:
  postgres_data:
  app_data: