# Generated by Django 5.1.6 on 2025-02-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('series_instance_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deidentified_series_instance_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('series_date', models.DateField(blank=True, null=True)),
                ('deidentified_series_date', models.DateField(blank=True, null=True)),
                ('frame_of_reference_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('deidentified_frame_of_reference_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('study_instance_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deidentified_study_instance_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('deidentified_study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=100, null=True)),
                ('study_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deidentified_study_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deidentified_patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_birth_date', models.DateField(blank=True, null=True)),
                ('deidentified_patient_birth_date', models.DateField(blank=True, null=True)),
                ('deidentified_patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomInstance',
            fields=[
                ('sop_instance_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deidentified_sop_instance_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deidapp.dicomseries')),
            ],
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deidapp.dicomstudy'),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deidapp.patient'),
        ),
        migrations.CreateModel(
            name='RTStructFile',
            fields=[
                ('series_instance_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('original_file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deidapp.dicomseries')),
            ],
        ),
    ]
