# Generated by Django 5.1.6 on 2025-02-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtstructfile',
            name='dicom_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deidapp.dicomseries'),
        ),
    ]
