# Generated by Django 5.1.7 on 2025-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deidapp', '0002_alter_rtstructfile_dicom_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
