# Generated by Django 5.1.7 on 2025-04-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deidapp', '0003_dicomseries_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='dicom_series_processing_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
