# Generated by Django 5.1.7 on 2025-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deidapp', '0004_dicomseries_dicom_series_processing_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dicominstance',
            index=models.Index(fields=['deidentified_sop_instance_uid'], name='deidapp_dic_deident_721cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomseries',
            index=models.Index(fields=['deidentified_series_instance_uid', 'series_date', 'deidentified_series_date', 'frame_of_reference_uid', 'deidentified_frame_of_reference_uid'], name='deidapp_dic_deident_d4cc69_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomstudy',
            index=models.Index(fields=['deidentified_study_instance_uid', 'study_date', 'deidentified_study_date'], name='deidapp_dic_deident_e8c79e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['deidentified_patient_id', 'patient_name', 'deidentified_patient_birth_date', 'deidentified_patient_name'], name='deidapp_pat_deident_430399_idx'),
        ),
    ]
