# Generated by Django 5.1.4 on 2025-01-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyDicom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcedirname', models.TextField()),
                ('destinationdirname', models.TextField()),
                ('dircreateddate', models.DateTimeField(null=True)),
                ('dirmodifieddate', models.DateTimeField(null=True)),
                ('dirsize', models.PositiveIntegerField()),
                ('copydate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Copy Dicom',
                'db_table': 'copy_dicom',
            },
        ),
        migrations.CreateModel(
            name='DicomImportConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pullinterval', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DicomPathConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datastorepath', models.TextField(null=True)),
                ('dicomimportfolderpath', models.TextField(null=True)),
                ('dicomprocessingfolderpath', models.TextField(null=True)),
                ('dicomnonprocessedfolderpath', models.TextField(null=True)),
                ('deidentificationfolderpath', models.TextField(null=True)),
                ('finalrtstructfolderpath', models.TextField(null=True)),
                ('templatefolderpath', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Dicom Path Configaration',
                'db_table': 'dicom_path_config',
            },
        ),
        migrations.CreateModel(
            name='DicomSeriesProcessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(max_length=10)),
                ('patientname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('studyid', models.CharField(max_length=255)),
                ('seriesid', models.CharField(max_length=255)),
                ('seriesfilepath', models.TextField()),
                ('studydate', models.DateField()),
                ('modality', models.CharField(max_length=10)),
                ('protocol', models.CharField(max_length=255, null=True)),
                ('sop_instance_uid', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('dicomcount', models.PositiveSmallIntegerField(null=True)),
                ('series_split_done', models.BooleanField(default=False)),
                ('processing_start', models.DateTimeField(null=True)),
                ('processing_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Dicom Import',
                'db_table': 'dicom_import',
            },
        ),
        migrations.CreateModel(
            name='ModelYamlInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaml_name', models.CharField(max_length=255)),
                ('yaml_path', models.TextField()),
                ('protocol', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=128, null=True)),
                ('yaml_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Yaml Info',
                'db_table': 'model_yaml_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tag Name',
                'db_table': 'tag_name',
            },
        ),
        migrations.CreateModel(
            name='DicomUnprocessed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(max_length=10)),
                ('patientname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('series_folder_location', models.TextField(null=True)),
                ('studyid', models.CharField(max_length=255)),
                ('seriesid', models.CharField(max_length=255)),
                ('studydate', models.DateField()),
                ('modality', models.CharField(max_length=10)),
                ('protocol', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('dicomcount', models.PositiveSmallIntegerField(null=True)),
                ('unprocessed', models.BooleanField(default=False, null=True)),
                ('processing_start', models.DateTimeField(null=True)),
                ('processing_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('yaml_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.modelyamlinfo')),
            ],
            options={
                'verbose_name': 'Dicom Unprocessed',
                'db_table': 'dicom_unprocessed',
            },
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255, null=True)),
                ('dicom_move_folder_status', models.CharField(max_length=255)),
                ('yaml_attach_status', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.dicomunprocessed')),
            ],
            options={
                'verbose_name': 'Processed Status',
                'db_table': 'processed_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_set_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('model_yaml', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.modelyamlinfo')),
            ],
            options={
                'verbose_name': 'Rule Set',
                'db_table': 'rule_set',
            },
        ),
        migrations.CreateModel(
            name='SeriesMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('tagname', models.CharField(max_length=255)),
                ('tagvalue', models.TextField()),
                ('series', models.ForeignKey(db_column='seriesid', on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.dicomseriesprocessing')),
            ],
            options={
                'verbose_name': 'Series Metadata',
                'db_table': 'series_metadata',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.ruleset')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.tagname')),
            ],
            options={
                'verbose_name': 'Rule',
                'db_table': 'rule',
            },
        ),
    ]
