# Generated by Django 5.1.4 on 2025-01-15 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomunprocessed',
            options={'verbose_name': 'Unprocessed DICOM Data', 'verbose_name_plural': 'Unprocessed DICOM Data'},
        ),
        migrations.AlterModelOptions(
            name='modelyamlinfo',
            options={'managed': True, 'verbose_name': 'Autosegemntation Template'},
        ),
        migrations.AlterModelOptions(
            name='processingstatus',
            options={'verbose_name': 'DICOM Processing Status', 'verbose_name_plural': 'DICOM Processing Status'},
        ),
        migrations.AlterModelOptions(
            name='ruleset',
            options={'verbose_name': 'Rule Set For Matching Template', 'verbose_name_plural': 'Rule Sets For Matching Template'},
        ),
        migrations.AlterModelOptions(
            name='tagname',
            options={'verbose_name': 'DICOM Tag List', 'verbose_name_plural': 'DICOM Tag List'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicom_handler.ruleset'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='tag_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicom_handler.tagname'),
        ),
    ]
