# Generated by Django 5.1.4 on 2025-01-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0002_alter_dicomunprocessed_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadDicom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dicom_file', models.FileField(upload_to='dicom_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='modelyamlinfo',
            options={'managed': True, 'verbose_name': 'Autosegmentation Template'},
        ),
    ]
