# Generated by Django 5.1.7 on 2025-04-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0002_auto_20250330_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CopyDicom',
        ),
        migrations.RemoveField(
            model_name='seriesmetadata',
            name='series',
        ),
        migrations.RemoveField(
            model_name='dicomunprocessed',
            name='yaml_attached',
        ),
        migrations.RemoveField(
            model_name='processingstatus',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='uploadDicom',
        ),
        migrations.DeleteModel(
            name='DicomSeriesProcessing',
        ),
        migrations.DeleteModel(
            name='SeriesMetaData',
        ),
        migrations.DeleteModel(
            name='DicomUnprocessed',
        ),
        migrations.DeleteModel(
            name='ProcessingStatus',
        ),
    ]
