# Generated by Django 5.1.7 on 2025-04-09 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0003_delete_copydicom_remove_seriesmetadata_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicompathconfig',
            name='date_time_to_start_pulling_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the date and time to start pulling data from the datastore. This setting can be changed manually at a later time to trigger a new pull of the data from the datastore.', null=True),
        ),
    ]
