# Generated by Django 5.1.4 on 2025-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0003_uploaddicom_alter_modelyamlinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddicom',
            name='dicom_file',
            field=models.FileField(upload_to='uploaddicom/'),
        ),
    ]
