# Generated by Django 5.1.4 on 2025-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0005_uploaddicom_send_to_autosegmentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddicom',
            name='dicom_file',
            field=models.FileField(upload_to=''),
        ),
    ]
