# Generated by Django 5.1.4 on 2025-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0008_alter_uploaddicom_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyamlinfo',
            name='yaml_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
