# Generated by Django 5.1.4 on 2025-03-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0010_alter_dicompathconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomseriesprocessing',
            options={'verbose_name': 'Dicom Series Split', 'verbose_name_plural': 'Dicom Series Split'},
        ),
        migrations.RemoveField(
            model_name='dicomseriesprocessing',
            name='sop_instance_uid',
        ),
        migrations.AddField(
            model_name='copydicom',
            name='processing_status',
            field=models.CharField(choices=[('COPIED', 'Copied'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='description',
            field=models.CharField(help_text='Enter a description for the rule set.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='model_yaml',
            field=models.OneToOneField(help_text='Select the model yaml file for the rule set.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.modelyamlinfo'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='rule_set_name',
            field=models.CharField(help_text='Enter a name for the rule set. This must be a unique name and not match any other existing rule set.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='tag_name',
            field=models.CharField(help_text='Enter the DICOM tag name. Please ensure that it matches the DICOM tag name properly', max_length=255),
        ),
    ]
