# Generated by Django 5.1.4 on 2025-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0011_alter_dicomseriesprocessing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copydicom',
            options={'verbose_name': 'Copied DICOM Data', 'verbose_name_plural': 'Copied DICOM Data'},
        ),
        migrations.AlterModelOptions(
            name='dicomseriesprocessing',
            options={'verbose_name': 'Dicom Series for Processing', 'verbose_name_plural': 'Dicom Series for Processing'},
        ),
        migrations.AlterField(
            model_name='copydicom',
            name='processing_status',
            field=models.CharField(choices=[('COPIED', 'COPIED'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddicom',
            name='dicom_file',
            field=models.FileField(upload_to='folder_for_dicom_upload/'),
        ),
    ]
