# Generated by Django 5.1.4 on 2025-03-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0012_alter_copydicom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicompathconfig',
            name='import_dicom',
        ),
    ]
