# Generated by Django 5.1.4 on 2025-03-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0013_remove_dicompathconfig_import_dicom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomunprocessed',
            name='ready_for_deidentification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dicompathconfig',
            name='datastorepath',
            field=models.TextField(help_text='Enter the full path to the datastore which is the remote folder from the DICOM data will be imported. This can be a remote folder in which case the full path is required. We would suggest that in such a situation the remote folder is mapped as a shared drive on the machine where this client runs.', null=True),
        ),
    ]
