# Generated by Django 5.1.4 on 2025-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0014_dicomunprocessed_ready_for_deidentification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseriesprocessing',
            name='origin_folder_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
