# Generated by Django 5.1.4 on 2025-03-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0015_dicomseriesprocessing_origin_folder_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DicomImportConfig',
        ),
        migrations.AlterModelOptions(
            name='dicompathconfig',
            options={'verbose_name': 'Dicom Path Configuration', 'verbose_name_plural': 'Dicom Path Configuration'},
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='modality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='origin_folder_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='patientname',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='protocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='seriesfilepath',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='studydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelyamlinfo',
            name='yaml_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
