# Generated by Django 5.1.7 on 2025-03-30 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0016_delete_dicomimportconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagname',
            name='tag_description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter the DICOM tag description. Please ensure that it matches the DICOM tag description properly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagname',
            name='tag_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter the DICOM tag id. Please ensure that it matches the DICOM tag id properly', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagname',
            name='value_representation',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter the DICOM tag value representation. Please ensure that it matches the DICOM tag value representation properly', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dicompathconfig',
            name='datastorepath',
            field=models.TextField(default='/app/datastore', help_text='Enter the full path to the datastore which is the remote folder from the DICOM data will be imported. This can be a remote folder in which case the full path is required. We would suggest that in such a situation the remote folder is mapped as a shared drive on the machine where this client runs.', null=True),
        ),
    ]
