# Generated by Django 5.1.7 on 2025-03-30 06:24

import csv
import os
from django.db import migrations
from django.conf import settings

def load_dicom_dictionary(apps, schema_editor):
    # Get the TagName model from the app registry
    TagName = apps.get_model('dicom_handler', 'TagName')
    
    # Path to CSV file - adjust this if needed
    csv_file_path = os.path.join(settings.BASE_DIR, 'seed_data', 'dicom_dictionary.csv')
    
    # Open and read the CSV file
    with open(csv_file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        
        # Create a TagName object for each row in the CSV
        for row in reader:
            TagName.objects.create(
                tag_id=row['tag_id'],
                tag_name=row['tag_name'],
                tag_description=row['tag_description'],
                value_representation=row['value_representation']
            )

def reverse_func(apps, schema_editor):
    # Delete all TagName objects to reverse the migration
    TagName = apps.get_model('dicom_handler', 'TagName')
    TagName.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0017_tagname_tag_description_tagname_tag_id_and_more'),
    ]

    operations = [
        migrations.RunPython(load_dicom_dictionary, reverse_func),
    ]
