# Generated by Django 5.1.7 on 2025-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0017_tagname_tag_description_tagname_tag_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='gender',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='modality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessing',
            name='patientid',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='dicomunprocessed',
            name='gender',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dicomunprocessed',
            name='modality',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dicomunprocessed',
            name='patientid',
            field=models.CharField(max_length=255),
        ),
    ]
