# Generated by Django 5.1.7 on 2025-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0019_alter_dicomseriesprocessing_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copydicom',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
