# Generated by Django 5.1.6 on 2025-03-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomtransfer',
            name='server_status',
            field=models.CharField(blank=True, help_text='Status reported by the server', max_length=255, null=True),
        ),
    ]
