# Generated by Django 5.1.6 on 2025-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0002_dicomtransfer_server_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.AlterField(
            model_name='dicomtransfer',
            name='rtstruct_file_path',
            field=models.CharField(blank=True, help_text='Path to the RTSTRUCT file (relative to base directory)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dicomtransfer',
            name='zip_file_path',
            field=models.CharField(help_text='Path to the zip file (relative to base directory)', max_length=512),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='archive_folder',
            field=models.CharField(help_text='Archive directory for processed DICOM files (relative to base directory)', max_length=512, verbose_name='Archive Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='output_folder',
            field=models.CharField(help_text='Output directory for received RTSTRUCT files (relative to base directory)', max_length=512, verbose_name='Output Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='temp_folder',
            field=models.CharField(help_text='Temporary directory for processing DICOM files (relative to base directory)', max_length=512, verbose_name='Temporary Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='watch_folder',
            field=models.CharField(help_text='Directory to monitor for new DICOM files (relative to base directory)', max_length=512, verbose_name='DICOM Watch Folder'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='download_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}', help_text='Endpoint for downloading RTSTRUCT files. Use {task_id} as placeholder.', max_length=200, verbose_name='Download Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='status_endpoint',
            field=models.CharField(default='api/upload/{task_id}/status/', help_text='Endpoint for checking segmentation status. Use {task_id} as placeholder.', max_length=200, verbose_name='Status Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='upload_endpoint',
            field=models.CharField(default='api/upload/', help_text='Endpoint for uploading DICOM files', max_length=200, verbose_name='Upload Endpoint'),
        ),
    ]
