# Generated by Django 5.1.4 on 2025-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0002_dicomtransfer_server_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='download_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}', help_text='Endpoint for downloading RTSTRUCT files. Use {task_id} as placeholder.', max_length=200, verbose_name='Download Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='status_endpoint',
            field=models.CharField(default='api/upload/{task_id}/status/', help_text='Endpoint for checking segmentation status. Use {task_id} as placeholder.', max_length=200, verbose_name='Status Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='upload_endpoint',
            field=models.CharField(default='api/upload/', help_text='Endpoint for uploading DICOM files', max_length=200, verbose_name='Upload Endpoint'),
        ),
    ]
