# Generated by Django 5.1.4 on 2025-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0003_delete_apikey_alter_dicomtransfer_rtstruct_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderpaths',
            name='archive_folder',
            field=models.CharField(default='archive', help_text='Archive directory for processed DICOM files (relative to base directory)', max_length=512, verbose_name='Archive Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='output_folder',
            field=models.CharField(default='rtstruct', help_text='Output directory for received RTSTRUCT files (relative to base directory)', max_length=512, verbose_name='Output Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='temp_folder',
            field=models.CharField(default='temporary', help_text='Temporary directory for processing DICOM files (relative to base directory)', max_length=512, verbose_name='Temporary Folder'),
        ),
        migrations.AlterField(
            model_name='folderpaths',
            name='watch_folder',
            field=models.CharField(default='processed_dicom', help_text='Directory to monitor for new DICOM files (relative to base directory)', max_length=512, verbose_name='DICOM Watch Folder'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='download_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}', help_text='Endpoint for downloading RTSTRUCT files. Use {task_id} as placeholder for the transaction ID provided by the server..', max_length=200, verbose_name='Download Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='notify_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}/confirm', help_text='Endpoint for notifying about RTSTRUCT receipt. Use {task_id} as placeholder for the transaction ID provided by the server.', max_length=200, verbose_name='Notify Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='status_endpoint',
            field=models.CharField(default='api/upload/{task_id}/status/', help_text='Endpoint for checking segmentation status. Use {task_id} as placeholder for the transaction ID provided by the server..', max_length=200, verbose_name='Status Endpoint'),
        ),
    ]
