# Generated by Django 5.1.4 on 2025-03-23 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0004_alter_folderpaths_archive_folder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderPaths',
        ),
    ]
