# Generated by Django 5.1.4 on 2025-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0005_delete_folderpaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='download_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}/', help_text='Endpoint for downloading RTSTRUCT files. Use {task_id} as placeholder for the transaction ID provided by the server. IMPORTANT: The trailing slash is required.', max_length=200, verbose_name='Download Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='notify_endpoint',
            field=models.CharField(default='api/rtstruct/{task_id}/confirm/', help_text='Endpoint for notifying about RTSTRUCT receipt. Use {task_id} as placeholder for the transaction ID provided by the server. IMPORTANT: The trailing slash is required.', max_length=200, verbose_name='Notify Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='status_endpoint',
            field=models.CharField(default='api/upload/{task_id}/status/', help_text='Endpoint for checking segmentation status. Use {task_id} as placeholder for the transaction ID provided by the server. IMPORTANT: The trailing slash is required.', max_length=200, verbose_name='Status Endpoint'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='upload_endpoint',
            field=models.CharField(default='api/upload/', help_text='Endpoint for uploading DICOM files. IMPORTANT: The trailing slash is required.', max_length=200, verbose_name='Upload Endpoint'),
        ),
    ]
