services:
  db:
    image: postgres:17
    restart: unless-stopped    
    container_name: postgres-docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    container_name: rabbitmq-docker
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  django-web:
    image: chaviapp/drawclient
    restart: unless-stopped
    container_name: django-docker
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env      
    volumes:
      - app_data:/app
      - ./staticfiles:/app/staticfiles
      - ./dicom:/app/folders
      - ./yaml-templates:/app/yaml-templates
      - "dicomdata:/app/datastore"
    command: ["./entrypoint.docker.sh"]
    environment:
      - DOCKER_CONTAINER=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  celery:
    image: chaviapp/drawclient
    restart: unless-stopped
    container_name: celery-docker
    command: ["./entrypoint.docker.sh", "celery"]
    volumes:
      - app_data:/app
      - ./staticfiles:/app/staticfiles
      - ./dicom:/app/folders      
      - ./yaml-templates:/app/yaml-templates
      - "dicomdata:/app/datastore" 
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=true
    depends_on:
      db:
        condition: service_healthy
      django-web:
        condition: service_started
      rabbitmq:
        condition: service_started
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  celery-beat:
    image: chaviapp/drawclient  
    restart: unless-stopped
    container_name: celery-beat-docker
    command: ["./entrypoint.docker.sh", "celery-beat"]
    volumes:
      - app_data:/app
      - ./staticfiles:/app/staticfiles
      - ./dicom:/app/folders
      - ./yaml-templates:/app/yaml-templates
      - "dicomdata:/app/datastore" 
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=true
    depends_on:
      db:
        condition: service_healthy
      django-web:
        condition: service_started
      rabbitmq:
        condition: service_started
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  frontend-proxy:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx-docker
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/staticfiles:ro
    depends_on:
      - django-web

# Use this section if you are using shared network storage
volumes:
  postgres_data:
  app_data:
  dicomdata:
    driver_opts:
      type: cifs
      o: "username=${NETWORK_USER},domain=${NETWORK_DOMAIN},password=${NETWORK_PASSWORD},rw,uid=1000,gid=1000,file_mode=0660,dir_mode=0770"
      device: ${NETWORK_PATH}  

# Use this section if you are using local storage. In the example below the D:/dicomdata is the path to the datastore on the local computer.
# volumes:
#   postgres_data:
#   app_data:
#   dicomdata:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: "D:/dicomdata"      