# Generated by Django 5.1.7 on 2025-03-31 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicom_handler', '0002_auto_20250330_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyDicomTaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_directory', models.CharField(blank=True, help_text='The source directory of the DICOM files', max_length=512, unique=True)),
                ('source_directory_creation_date', models.DateTimeField(blank=True)),
                ('source_directory_modification_date', models.DateTimeField(blank=True)),
                ('source_directory_size', models.BigIntegerField(blank=True)),
                ('target_directory', models.CharField(blank=True, max_length=512)),
                ('task_id', models.CharField(blank=True, help_text='The task id of the celery task that processed the series', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Copy DICOM Task',
                'verbose_name_plural': 'Copy DICOM Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DicomSeriesProcessingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=255)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('scan_date', models.DateField(blank=True)),
                ('modality', models.CharField(blank=True, max_length=50)),
                ('study_instance_uid', models.CharField(blank=True, max_length=255)),
                ('series_instance_uid', models.CharField(blank=True, max_length=255)),
                ('series_description', models.CharField(blank=True, max_length=255)),
                ('series_import_directory', models.CharField(blank=True, max_length=512)),
                ('series_current_directory', models.CharField(blank=True, max_length=512)),
                ('processing_status', models.CharField(blank=True, choices=[('SERIES_SEPARATED', 'Series Separated'), ('TEMPLATE_NOT_MATCHED', 'Template Not Matched'), ('MULTIPLE_TEMPLATES_MATCHED', 'Multiple Templates Matched'), ('MULTIPLE_TEMPLATES_FOUND', 'Multiple Templates Found'), ('NO_TEMPLATE_FOUND', 'No Template Found'), ('READY_FOR_DEIDENTIFICATION', 'Ready For Deidentification'), ('DEIDENTIFIED', 'Deidentified'), ('DEIDENTIFICATION_FAILED', 'Deidentification Failed'), ('RTSTRUCT_EXPORT_FAILED', 'Rtstruct Export Failed'), ('RTSTRUCT_EXPORTED', 'Rtstruct Exported'), ('ERROR', 'Error')], max_length=60)),
                ('series_state', models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('UNPROCESSED', 'Unprocessed'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy_dicom_task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicomapp.copydicomtaskmodel')),
                ('template_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dicom_handler.modelyamlinfo')),
            ],
            options={
                'verbose_name': 'Dicom Series Processing',
                'verbose_name_plural': 'Dicom Series Processing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DicomSeriesProcessingLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, help_text='The task id of the celery task that processed the series', max_length=255)),
                ('processing_status', models.CharField(blank=True, choices=[('SERIES_SEPARATED', 'Series Separated'), ('TEMPLATE_NOT_MATCHED', 'Template Not Matched'), ('MULTIPLE_TEMPLATES_MATCHED', 'Multiple Templates Matched'), ('MULTIPLE_TEMPLATES_FOUND', 'Multiple Templates Found'), ('NO_TEMPLATE_FOUND', 'No Template Found'), ('READY_FOR_DEIDENTIFICATION', 'Ready For Deidentification'), ('DEIDENTIFIED', 'Deidentified'), ('DEIDENTIFICATION_FAILED', 'Deidentification Failed'), ('RTSTRUCT_EXPORT_FAILED', 'Rtstruct Export Failed'), ('RTSTRUCT_EXPORTED', 'Rtstruct Exported'), ('ERROR', 'Error')], max_length=60)),
                ('processing_status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_series_processing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicomapp.dicomseriesprocessingmodel')),
            ],
            options={
                'verbose_name': 'Dicom Series Processing Log',
                'verbose_name_plural': 'Dicom Series Processing Logs',
            },
        ),
    ]
