# Generated by Django 5.1.7 on 2025-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0002_dicomseriesprocessingmodel_protocol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='protocol_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='series_current_directory',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='series_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseriesprocessingmodel',
            name='series_import_directory',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
