# Generated by Django 5.1.7 on 2025-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0002_remove_dicomseriesprocessingmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='copydicomtaskmodel',
            name='copy_completed',
            field=models.BooleanField(default=False),
        ),
    ]
