# Generated by Django 5.1.7 on 2025-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0003_alter_dicomseriesprocessingmodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseriesprocessingmodel',
            name='series_archive_directory',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
