# Generated by Django 5.1.7 on 2025-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0004_dicompathconfig_date_time_to_start_pulling_data'),
        ('dicomapp', '0004_dicomseriesprocessingmodel_series_archive_directory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dicomseriesprocessingmodel',
            index=models.Index(fields=['patient_id', 'series_instance_uid', 'study_instance_uid'], name='dicomapp_di_patient_15a7f8_idx'),
        ),
    ]
